//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaixaEletronico.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class conta
    {
        public string cpf { get; set; }
        public Nullable<int> numConta { get; set; }
        public Nullable<int> numAgencia { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public string email { get; set; }
        public Nullable<decimal> saldo { get; set; }
    }
}
