//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaixaEletronico.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class historico
    {
        public int id_historico { get; set; }
        public string cpf { get; set; }
        public string texto { get; set; }
    }
}
